import { analytics } from '@/services/analyticsService';
import { Alert,Platform } from 'react-native';

const webShare = async (text: string, title: string): Promise<boolean> => {
  if (typeof navigator !== 'undefined' && navigator.share) {
    try {
      await navigator.share({ title, text });
      return true;
    } catch {
      return false;
    }
  }
  if (typeof navigator !== 'undefined' && navigator.clipboard) {
    try {
      await navigator.clipboard.writeText(text);
      Alert.alert('Copied!', 'Story copied to clipboard.');
      return true;
    } catch {
      return false;
    }
  }
  return false;
};

const nativeShare = async (text: string): Promise<boolean> => {
  try {
    const FileSystem = require('expo-file-system');
    const Sharing = require('expo-sharing');

    const canShare = await Sharing.isAvailableAsync();
    if (!canShare) return false;

    const tempFile = FileSystem.cacheDirectory + 'story.txt';
    await FileSystem.writeAsStringAsync(tempFile, text);
    await Sharing.shareAsync(tempFile, { mimeType: 'text/plain', dialogTitle: 'Share' });
    return true;
  } catch {
    return false;
  }
};

export const shareStory = async (storyTitle: string, storyContent: string) => {
  try {
    const shareText = `"${storyTitle}"\n\n${storyContent.substring(0, 200)}${storyContent.length > 200 ? '...' : ''}\n\nGenerated by Jahera`;

    const shared = Platform.OS === 'web'
      ? await webShare(shareText, storyTitle)
      : await nativeShare(shareText);

    if (shared) {
      analytics.trackEngagement('story_shared', { story_title: storyTitle });
    } else {
      Alert.alert('Sharing not available', 'Could not share on this device.');
    }
  } catch (error) {
    console.error('Failed to share story:', error);
  }
};

export const shareAchievement = async (achievementTitle: string, achievementDescription: string) => {
  try {
    const shareText = `Achievement Unlocked!\n\n${achievementTitle}\n${achievementDescription}\n\nFrom Jahera`;

    if (Platform.OS === 'web') {
      await webShare(shareText, achievementTitle);
    } else {
      await nativeShare(shareText);
    }

    analytics.trackEngagement('achievement_shared', { achievement: achievementTitle });
  } catch (error) {
    console.error('Failed to share achievement:', error);
  }
};

export const shareApp = async () => {
  try {
    const appLink = Platform.select({
      ios: 'https://apps.apple.com/app/jahera',
      android: 'https://play.google.com/store/apps/details?id=com.jahera',
      default: 'https://jahera.app',
    });

    const shareText = `Check out Jahera - an amazing AI-powered story app for kids!\n\n${appLink}`;

    if (Platform.OS === 'web') {
      await webShare(shareText, 'Jahera - Kids Story App');
    } else {
      await nativeShare(shareText);
    }

    analytics.trackEngagement('app_shared');
  } catch (error) {
    console.error('Failed to share app:', error);
  }
};
