import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';
import { Platform, Alert } from 'react-native';
import { analytics } from '@/services/analyticsService';

/**
 * Share utilities for production-ready social sharing
 */

export const shareStory = async (storyTitle: string, storyContent: string, audioUri?: string) => {
  try {
    const canShare = await Sharing.isAvailableAsync();
    if (!canShare) {
      Alert.alert('Sharing not available', 'Sharing is not available on this device');
      return;
    }

    // Create a shareable text
    const shareText = `📖 Check out this story: "${storyTitle}"\n\n${storyContent.substring(0, 200)}${storyContent.length > 200 ? '...' : ''}\n\nGenerated by Jahera`;

    // For now, we'll share text. In production, you might want to create an image or PDF
    const tempFile = FileSystem.cacheDirectory + 'story.txt';
    await FileSystem.writeAsStringAsync(tempFile, shareText);

    await Sharing.shareAsync(tempFile, {
      mimeType: 'text/plain',
      dialogTitle: 'Share your story',
    });

    analytics.trackEngagement('story_shared', { story_title: storyTitle });
  } catch (error) {
    console.error('Failed to share story:', error);
    Alert.alert('Error', 'Failed to share story. Please try again.');
  }
};

export const shareAchievement = async (achievementTitle: string, achievementDescription: string) => {
  try {
    const canShare = await Sharing.isAvailableAsync();
    if (!canShare) {
      return;
    }

    const shareText = `🏆 Achievement Unlocked!\n\n${achievementTitle}\n${achievementDescription}\n\nFrom Jahera - Kids Story App`;

    const tempFile = FileSystem.cacheDirectory + 'achievement.txt';
    await FileSystem.writeAsStringAsync(tempFile, shareText);

    await Sharing.shareAsync(tempFile, {
      mimeType: 'text/plain',
      dialogTitle: 'Share your achievement',
    });

    analytics.trackEngagement('achievement_shared', { achievement: achievementTitle });
  } catch (error) {
    console.error('Failed to share achievement:', error);
  }
};

export const shareApp = async () => {
  try {
    const canShare = await Sharing.isAvailableAsync();
    if (!canShare) {
      return;
    }

    // In production, replace with actual app store links
    const appStoreLink = Platform.select({
      ios: 'https://apps.apple.com/app/jahera',
      android: 'https://play.google.com/store/apps/details?id=com.jahera',
      default: 'https://jahera.app',
    });

    const shareText = `Check out Jahera - an amazing AI-powered story app for kids! 📚✨\n\n${appStoreLink}`;

    const tempFile = FileSystem.cacheDirectory + 'share_app.txt';
    await FileSystem.writeAsStringAsync(tempFile, shareText);

    await Sharing.shareAsync(tempFile, {
      mimeType: 'text/plain',
      dialogTitle: 'Share Jahera',
    });

    analytics.trackEngagement('app_shared');
  } catch (error) {
    console.error('Failed to share app:', error);
  }
};
